### ISSUE TITLE
Add a developers page and a projects page in the website

### ISSUE THREAD

**Issue by Devnol** [terrific-tea/terrific-tea.github.io#1]
tomorrow:tm: we'll do that.

**Comment by Oxygemo** [comment]
Xuě huā piāo piāo běi fēng xiāo xiāo

**Comment by Oxygemo** [comment]
Isn't this kinda done

**Comment by Oxygemo** [comment]
Okay well developers is done-ish, people just need to make a bio and we can improve it later. Projects: I have an idea for this

**Comment by Odyssey346** [comment]
What the fuck, only now are you closing them?
