### ISSUE TITLE
Use Font Awesome, maybe?

### ISSUE THREAD

**Issue by Odyssey346** [terrific-tea/terrific-tea.github.io#11]
Font Awesome has rly good icons and its easy to embed into webpages, should we use Font Awesome? I like it, it seems pretty easy to implement aswell.

https://fontawesome.com

**Comment by Oxygemo** [comment]
@Rexogamer  can you assign me and @Devnol

**Comment by Oxygemo** [comment]
Just look at all these icons. You want to use them. https://fontawesome.com/icons?d=gallery

**Comment by Rexogamer** [comment]
Isn't it paid?

**Comment by Oxygemo** [comment]
Sorta, you can still use it free. I know Ruqqus does, because I had to use Font Awesome there.

**Comment by Oxygemo** [comment]
Yeah there's a lot of paid icons but for what we would probably need for the future, we should be set.

**Comment by Oxygemo** [comment]
@Devnol wdyt about this?

**Comment by Oxygemo** [comment]
What do you think, @Devnol? You're the website lead dev

**Comment by Devnol** [comment]
Sure I guess

**Comment by Midou36O** [comment]
![image](https://user-images.githubusercontent.com/45198486/102065916-72605900-3df9-11eb-986b-af98c8736dce.png)
sure why not

**Comment by Odyssey346** [comment]
you know what would be awesome? If this issue was closed!
