### ISSUE TITLE
Maybe add a site with reasons why TTS is gr8m8?

### ISSUE THREAD

**Issue by Odyssey346** [terrific-tea/terrific-tea.github.io#16]
I can do the site, but the reasons... I ain't a member here. Give reasons here, please

**Comment by Oxygemo** [comment]
@Rexogamer @Devnol

**Comment by Oxygemo** [comment]
My idea for one of the reasons is lgbt friendlyness

**Comment by Oxygemo** [comment]
@Rexogamer you got any reasons? I came up with one and it's above.

**Comment by Rexogamer** [comment]
- freedom with projects
- unique ideas
- friendly community

**Comment by Oxygemo** [comment]
> Freedom with projects
I fully agree.
> Unique ideas
Cytrus-RE wasn't that unique but yeah tru
> Friendly community
Absolutely.

Although, could you also write up why those are true?

**Comment by Oxygemo** [comment]
god dammit github's markdown is terrible

**Comment by Oxygemo** [comment]
Also maybe add that we're a serious not-serious developer group? It's debatable but I'm thinking that

**Comment by Rexogamer** [comment]
**Freedom with projects**
I've kinda let y'all work on what you want and so far most of y'all's project ideas have been accepted

**Unique ideas**
I can't really publicly reveal the stuff we haven't started working on, but stuff like Pie and that file thing

**Friendly community**
If you abide by the rules we're generally nice and helpful, not much to say here

**Comment by Rexogamer** [comment]
> Also maybe add that we're a serious not-serious developer group? It's debatable but I'm thinking that

not rly needed imo but maybe

**Comment by Oxygemo** [comment]
Okay, for me the end product of that would be:

Freedom with projects

We let everyone work on whatever they want to, and give those ideas to us and then we see if it's good. Most have been accepted. Think a nice idea and tell us, maybe we can make your dream come true? :eyes:

Unique ideas

We have some stuff in the works 🙈 that are unique and (to our knowledge) haven't been done before. Most of our current stuff is fresh and cool!

Friendly community

📜 If you can read the rules, then we're all good. Most of us aren't toxic to new people, as we want to grow!

Thoughts?

**Comment by Midou36O** [comment]
> maybe we can make your dream come true? :eyes: 

stay professional and don't sell dreams, most companies add some lies to attract the people and i don't want that tbh (for example the VPN that spams youtube sponsors)

**Comment by Oxygemo** [comment]
This GitHub issue was sponsored by OdysseyVPN

**Comment by Odyssey346** [comment]
yeah absolutely not
