### ISSUE TITLE
[META] Set up priority labels

### ISSUE THREAD

**Issue by Odyssey346** [terrific-tea/terrific-tea.github.io#17]
proiority-0, priority-1, priority-2, priority-3.

0: Needs to be done ASAP
1: Very important but we can do it later
2: Sorta nice to do, but it can wait
3: Last thing to do/Least prioritized.

I'd make them but I don't have write access here.

**Comment by Oxygemo** [comment]
Something like this 
![image](https://user-images.githubusercontent.com/57069715/101881572-e8b05180-3b94-11eb-96af-7fb652ce8117.png)

**Comment by Oxygemo** [comment]
This issue would be a priority-2.

**Comment by Odyssey346** [comment]
priority 0: close these fucking issues!
