### ISSUE TITLE
css: make it less bloat, create a consistent UI with less colours.

### ISSUE THREAD

**Issue by Devnol** [terrific-tea/terrific-tea.github.io#2]

**Comment by Devnol** [comment]
that too

**Comment by Oxygemo** [comment]
I don't think the CSS is that bloated.

**Comment by Oxygemo** [comment]
Hmm, for specific things I reckon we could split them up into different CSS files, like the Team Member Pages

**Comment by Midou36O** [comment]
> I don't think the CSS is that bloated.
i still think that rewriting the css is better, i can't code correctly with that spaghetti code we have, perhaps name the tags with actual names instead of just using html functions universally?
