### ISSUE TITLE
Make it more mobile friendly

### ISSUE THREAD

**Issue by Odyssey346** [terrific-tea/terrific-tea.github.io#3]
I like the work you guys have done, but one thing that should be put on your radar is making it better for mobile. 
![Screenshot_20201110-064302745](https://user-images.githubusercontent.com/57069715/98632641-2b75d400-2320-11eb-853f-7bf14bf27839.jpg)
![Screenshot_20201110-064256352](https://user-images.githubusercontent.com/57069715/98632642-2ca70100-2320-11eb-9762-4d0cb18c450d.jpg)

**Comment by Midou36O** [comment]
Gonna work on it

**Comment by Oxygemo** [comment]
Maybe we can put the header (tts logo and buttons) into a hamburger menu thing so that it doesn't take up a lot of space on mobile?

**Comment by Rexogamer** [comment]
A hamburger menu would be a good idea.

**Comment by Oxygemo** [comment]
![image](https://user-images.githubusercontent.com/57069715/101797129-f8368880-3b09-11eb-9f57-66011d468417.png)
excuse my shitty drawing but this is what I want it to look at

**Comment by Oxygemo** [comment]
Essentially, we have the logo on the left, and links and stuff into a hamburger menu

**Comment by Rexogamer** [comment]
That's what I was thinking, also nice uwu lmao

**Comment by Oxygemo** [comment]
I had to save space... I planned to draw a cock there but we're professionals: we have standards.

**Comment by Oxygemo** [comment]
funny haha reference at: https://youtu.be/9NZDwZbyDus?t=68

**Comment by Midou36O** [comment]
Do we make a website powered javascript or not? (like the mobile friendly implementation i did doesn't use javascript at all for privacy reasons (people who disable javascript and tor users too)

**Comment by Oxygemo** [comment]
mobile users don't really disable js so i think we're fine

**Comment by Odyssey346** [comment]
fuck this shit
